In [10]:
import numpy as np

# assume pose_rotvec is a 2D numpy array with shape (n, m)
poses = np.random.randint(0, 10, size=(10, 6))

print(poses)

# select the first three columns of pose_rotvec


# print the resulting array
print(poses[0:2, :])

[[7 6 1 2 6 3]
 [7 7 7 7 5 9]
 [2 2 5 0 3 8]
 [3 6 8 9 2 9]
 [6 5 4 1 8 4]
 [9 7 0 5 3 8]
 [9 5 5 4 8 2]
 [4 0 6 6 9 7]
 [3 9 1 8 2 3]
 [7 0 9 6 3 1]]
[[7 6 1 2 6 3]
 [7 7 7 7 5 9]]


In [3]:
import jukemirlib

audio = jukemirlib.load_audio('/home/yiyu/JustLM2D/Songs_2020/badguyBillieEilishJustDance2020/audio.wav')

reps = jukemirlib.extract(audio, layers=[36])

Importing jukebox and associated packages...
Setting up the VQ-VAE...
Loading vqvae in eval mode
Setting up the top prior...
Loading artist IDs from /home/yiyu/miniconda3/lib/python3.8/site-packages/jukebox/data/ids/v2_artist_ids.txt
Loading artist IDs from /home/yiyu/miniconda3/lib/python3.8/site-packages/jukebox/data/ids/v2_genre_ids.txt
Level:2, Cond downsample:None, Raw to tokens:128, Sample length:1048576
Converting to fp16 params
Loading prior in eval mode
Loading the top prior weights into memory...


100%|██████████| 669/669 [00:00<00:00, 17865.83it/s]


In [8]:
print(reps[36].shape)

(8192, 4800)


In [15]:
import clip
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model, preprocess = clip.load("RN50", device=device)

lyrics = "Your lyrics here, hi, it's me, I've been wonder if after all these year you'd like to me"  # Replace with your actual lyrics

# Preprocess the lyrics
lyrics_tokens = lyrics.split()
lyrics_preprocessed = " ".join(lyrics_tokens)
# text_input = clip.tokenize([lyrics_preprocessed]).to(device)
text_input = clip.tokenize(['Hello','Its', 'me']).to(device)

with torch.no_grad():
    lyrics_features = model.encode_text(text_input)
    print(lyrics_features.shape)

torch.Size([3, 1024])
