In [10]:
import numpy as np

# assume pose_rotvec is a 2D numpy array with shape (n, m)
poses = np.random.randint(0, 10, size=(10, 6))

print(poses)

# select the first three columns of pose_rotvec


# print the resulting array
print(poses[0:2, :])

[[7 6 1 2 6 3]
 [7 7 7 7 5 9]
 [2 2 5 0 3 8]
 [3 6 8 9 2 9]
 [6 5 4 1 8 4]
 [9 7 0 5 3 8]
 [9 5 5 4 8 2]
 [4 0 6 6 9 7]
 [3 9 1 8 2 3]
 [7 0 9 6 3 1]]
[[7 6 1 2 6 3]
 [7 7 7 7 5 9]]
